name: xcube
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python >=3.6
  # Required
  - affine >=2.2
  - blas =*.*=mkl
  - click >=7.0
  - cmocean >=2.0
  - dask >=1.2
  - fiona >=1.8
  - gdal >=2.4
  - geopandas >=0.6.2
  - jdcal>=1.4.1
  - jsonschema >=3.2.0
  - matplotlib >=3.0
  - netcdf4 >=1.5.0
  - numba >=0.43
  - numpy >=1.16
  - pandas >=0.24, <=1.0 #  https://github.com/pydata/xarray/commit/59f57f3e410aca19a722c4a0d84359bde9852fbf restriction of pandas should be removed with new xarray release
  - pillow >=6.0
  - proj4 >=5.2
  - pyjwt >= 1.7
  - pyproj >=2.1
  - pyyaml >=5.1
  - rasterio >=1.0
  - s3fs >=0.5.1
  - scipy >=1.2
  - setuptools >=41.0
  - shapely >=1.6
  - tornado >=6.0
  - xarray >=0.14.1
  - zarr >=2.3.2
  - sphinx >=2.0.1
  # Testing
  - flake8 >=3.7
  - moto >=1.3
  - moto[server]
  - pytest >=4.4
  - pytest-cov >=2.6
  - requests-mock >= 1.8.0
